version: '3.8'

networks:
  outside-nw:

services:
  music:
    image: 'joinc/music'
    ports:
      - 8088
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.music.rule=PathPrefix("/music")
      - traefik.http.services.music.loadbalancer.server.port=8088
    networks:
      - outside-nw

  image:
    image: 'joinc/image'
    ports:
      - 8088
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.image.rule=PathPrefix("/image")
      - traefik.http.services.image.loadbalancer.server.port=8088
    networks:
      - outside-nw

  load-balancer:
    image: 'traefik:v2.3'
    command: >
      --providers.docker=true
      --providers.docker.exposedbydefault=false
      --entryPoints.http.address=":80"
      --accesslog
      --log.level=INFO
      --api=true
      --api.insecure=true
      --api.dashboard=true
    ports:
      - "80:80"  # load balancer port
      - "8080:8080"  # management UI
    volumes:
      # traefik does its magic by reading information about running containers from the docker socket
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - outside-nw
    depends_on:
      - music
      - image
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik_http.service=api@internal
      - traefik.http.routers.traefik_http.entrypoints=http